[package]
name = "rust_gpiozero_demo"
version = "0.1.0"
authors = ["Andre Larberg <andilar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_gpiozero = "0.2.0"
